name: clouds
base: core22
assumes:
  - snapd2.43
version: '0.666'
summary: Download, install, and run Windows in a VM
description: |
  Download, install, and run Windows 10 or 11 in a VM.

  The app will walk you through downloading a Windows DVD image, and launch the installation. Most of the installation is automated to reduce the chance of errors while installing. Once Windows is installed Clouds will boot directly into the operating system whenever you launch the app.

grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/qemu:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qemu
  /usr/lib/ipxe:
    bind: $SNAP/usr/lib/ipxe
  /usr/lib/p7zip:
    bind: $SNAP/usr/lib/p7zip
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/share/seabios:
    bind: $SNAP/usr/share/seabios
  /usr/share/qemu:
    bind: $SNAP/usr/share/qemu

environment:
  PYTHONHOME: $SNAP/gnome-platform/usr
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages

apps:
  clouds:
    extensions: [gnome]
    command: bin/clouds
    plugs:
      - audio-playback
      - audio-record
      - home
      - kvm
      - network
      - network-bind
      - network-control
      - raw-usb
      - removable-media
      - screen-inhibit-control
  mid:
    command: usr/bin/fluidsynth -nia pulseaudio $SNAP/soundfont.sf3 $SNAP/CLOUDS.MID
    extensions: [gnome]
    plugs:
      - audio-playback
  mp3:
    command: usr/bin/mpg123.bin -o pulse $SNAP/clouds.mp3
    environment:
      MPG123_MODDIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/mpg123
    extensions: [gnome]
    plugs:
      - audio-playback

parts:
  npm-deps:
    plugin: dump
    source: https://nodejs.org/dist/v16.18.0/node-v16.18.0-linux-x64.tar.xz
    stage:
      - -include
      - -share
    prime:
      - -bin/corepack
      - -bin/npm
      - -bin/npx
      - -lib

  downloader:
    after: [npm-deps]
    plugin: npm
    source: downloader

  config:
    plugin: dump
    source: config
    build-packages:
      - genisoimage
      - wimtools

  egg:
    plugin: dump
    source: egg
    stage-packages:
      - fluidsynth
      - mpg123
    stage:
      - -etc/default
      - -usr/lib/mime
      - -usr/lib/systemd

  soundfont:
    plugin: dump
    source: egg
    override-pull: |
      curl -o soundfont.sf3 https://ftp.osuosl.org/pub/musescore/soundfont/MuseScore_General/MuseScore_General.sf3
    stage:
      - -README
    build-packages:
      - curl

  virtio-drivers:
    plugin: dump
    source: config
    override-pull: |
      wget https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso -O virtio-win.iso
    build-packages:
      - wget

  clouds:
    plugin: dump
    source: snap/local
    stage-packages:
      - qemu-system-gui
      - qemu-system-x86
      - qemu-utils
      - yad               # to do dialogs
      - ovmf
      - seabios
      - swtpm
      - fonts-ubuntu
      - cpu-checker
      - genisoimage
      - p7zip-full
      - python3-xmltodict
      - util-linux
      - wget
      - wimtools
    stage:
      - -bin/chacl
      - -bin/getfacl
      - -bin/setfacl
      - -etc/apparmor.d
      - -etc/default
      - -etc/init.d
      - -etc/X11
      - -lib/systemd
      - -usr/share/applications
      - -usr/share/icons
      - -usr/lib/ipxe/*.rom
      - -usr/lib/ipxe/qemu/efi-e1000.rom
      - -usr/lib/ipxe/qemu/efi-e1000e.rom
      - -usr/lib/ipxe/qemu/efi-eepro100.rom
      - -usr/lib/ipxe/qemu/efi-ne2k_pci.rom
      - -usr/lib/ipxe/qemu/efi-pcnet.rom
      - -usr/lib/ipxe/qemu/efi-rtl8139.rom
      - -usr/lib/ipxe/qemu/efi-vmxnet.rom
      - -usr/lib/ipxe/qemu/pxe-*.rom
      - -usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/gtk-3.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libatk-1.0*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libcairo*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libdecor-0*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libgdk-3*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libgtk-3*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libharfbuzz*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libpango*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXss.so*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXt.so*
      - -usr/share/qemu/bamboo.dtb
      - -usr/share/qemu/bios-microvm.bin
      - -usr/share/qemu/canyonlands.dtb
      - -usr/share/qemu/hppa-firmware.img
      - -usr/share/qemu/openbios-ppc
      - -usr/share/qemu/openbios-sparc32
      - -usr/share/qemu/openbios-sparc64
      - -usr/share/qemu/opensbi-riscv64-generic-fw_dynamic.bin
      - -usr/share/qemu/opensbi-riscv64-generic-fw_dynamic.elf
      - -usr/share/qemu/qboot.rom
      - -usr/share/qemu/s390-ccw.img
      - -usr/share/qemu/s390-netboot.img
      - -usr/share/qemu/skiboot.lib
      - -usr/share/qemu/slof.bin
      - -usr/share/qemu/trace-events-all
      - -usr/share/qemu/vof.bin

  cleanup:
    after:
      - clouds
      - config
      - egg
      - downloader
      - virtio-drivers
    plugin: nil
    build-snaps: [gnome-42-2204]  # List all content-snaps and base snaps you're using here
    override-prime: |
      set -eux
      for snap in "gnome-42-2204"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
      for CRUFT in aclocal bug info lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$CRUFT
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $CRAFT_PRIME/usr/share -type d -empty -delete
      find $CRAFT_PRIME/etc -type d -empty -delete
      find $CRAFT_PRIME/usr -type d -empty -delete
