name: clouds
base: core20
assumes:
  - snapd2.43
version: '0.666'
summary: Download and install Windows 10 in a VM
description: |
  Download and install Windows 10 in a VM

grade: stable
confinement: strict
compression: lzo

package-repositories:
  - type: apt
    ppa: diddledani/qemu

architectures:
  - build-on: amd64
    run-on: amd64

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu

apps:
  clouds:
    extensions: [gnome-3-38]
    command: bin/clouds
    plugs:
      - audio-playback
      - audio-record
      - desktop
      - home
      - kvm
      - network
      - network-bind
      - network-control
      - opengl
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - unity7
      - wayland
      - x11
  mid:
    command: usr/bin/fluidsynth -nia pulseaudio $SNAP/soundfont.sf3 $SNAP/CLOUDS.MID
    extensions: [gnome-3-38]
    plugs:
      - audio-playback
  mp3:
    command: usr/bin/mpg123.bin -o pulse $SNAP/clouds.mp3
    environment:
      MPG123_MODDIR: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mpg123
    extensions: [gnome-3-38]
    plugs:
      - audio-playback

parts:
  downloader:
    plugin: npm
    source: downloader
    npm-node-version: '14.17.6'

  config:
    plugin: nil
    source: config
    override-build: |
      mkisofs -l -o $SNAPCRAFT_PART_INSTALL/config.iso .
    build-packages:
      - genisoimage

  egg:
    plugin: dump
    source: egg
    stage-packages:
      - fluidsynth
      - mpg123

  soundfont:
    plugin: dump
    source: egg
    override-pull: |
      curl -o soundfont.sf3 https://ftp.osuosl.org/pub/musescore/soundfont/MuseScore_General/MuseScore_General.sf3
    stage:
      - -README
    build-packages:
      - curl

  virtio-drivers:
    plugin: dump
    source: .
    override-pull: |
      wget https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso -O virtio-win.iso
    build-packages:
      - wget

  clouds:
    plugin: dump
    source: snap/local
    stage-packages:
      - qemu-system-gui
      - qemu-system-x86
      - qemu-utils
      - yad               # to do dialogs
      - ovmf
      - seabios
      - swtpm
      - ttf-ubuntu-font-family
      - cpu-checker
      - wget
    stage:
      - -usr/share/qemu/hppa-firmware.bin
      - -usr/share/qemu/openbios-ppc
      - -usr/share/qemu/openbios-sparc32
      - -usr/share/qemu/openbios-sparc64
      - -usr/share/qemu/opensbi-risc64-generic-fw_dynamic.bin
      - -usr/share/qemu/opensbi-risc64-generic-fw_dynamic.elf

  cleanup:
    after:
      - downloader
      - config
      - virtio-drivers
      - clouds
    plugin: nil
    build-snaps: [gnome-3-38-2004]  # List all content-snaps and base snaps you're using here
    override-prime: |
      set -eux
      for snap in "gnome-3-38-2004"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
