name: Build Pull Requests

on:
- pull_request

jobs:
  snapcraft-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jhenstridge/snapcraft-build-action@v1
      id: build
    - uses: diddlesnaps/snapcraft-review-tools-action@v1
      with:
        snap: ${{ steps.build.outputs.snap }}
